services:
  redisstreamscope:
    container_name: redisstreamscope
    image: ghcr.io/ghkdqhrbals/redisstreamscope:latest
    ports:
      - "8080:8080"
    volumes:
      - redisstreamscope-data:/data
    restart: unless-stopped

volumes:
  redisstreamscope-data:
