services:
  streamscope:
    container_name: streamscope
    image: ghcr.io/ghkdqhrbals/streamscope:latest
    ports:
      - "8080:8080"
    volumes:
      - streamscope-data:/data
    restart: unless-stopped

volumes:
  streamscope-data:
