apiVersion: v1
kind: Service
metadata:
  name: {{ include "redisstreamscope.fullname" . | quote }}
  labels:
    {{- include "redisstreamscope.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | quote }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: "http"
  selector:
    {{- include "redisstreamscope.selectorLabels" . | nindent 4 }}
